name: CD | Getting repositories data in CSV format

on:
  schedule:
    - cron: '0 0/6 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: "getting-repositories-data"

jobs:
  generate-data:
    runs-on: ubuntu-latest

    env:
      LOCALES: "de en-us es fr ja ko pt-br ru zh-cn zh-tw"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.13.9'

      - name: Clone MDN content repo
        run: git clone https://github.com/mdn/content.git content

      - name: Clone MDN translated-content repo
        run: git clone https://github.com/mdn/translated-content.git translated-content

      - name: Clone MDN translated-content-de repo
        run: git clone https://github.com/mdn/translated-content-de.git translated-content-de

      - name: Generate logs files
        shell: bash
        run: |
          mkdir -p history
          for locale in $LOCALES; do
            if [ "$locale" = "en-us" ]; then
              python scripts/extract-mdn-logs.py content $locale
            elif [ "$locale" = "de" ]; then
              python scripts/extract-mdn-logs.py translated-content-de $locale
            else
              python scripts/extract-mdn-logs.py translated-content $locale
            fi
          done

      - uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd #v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 #v8.1.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          add-paths: history/*.csv
          commit-message: "sync(data): synchronize repositories data"
          committer: ${{ vars.GPG_COMMITTER }}
          author: ${{ vars.GPG_COMMITTER }}
          sign-commits: true
          title: "sync(data): synchronize repositories data"
          body: |
            This PR updates the repositories data in CSV format.
            - Updated en-us locale (default locale)
            - Updated de locale
            - Updated es locale
            - Updated fr locale
            - Updated ja locale
            - Updated ko locale
            - Updated pt-br locale
            - Updated ru locale
            - Updated zh-cn locale
            - Updated zh-tw locale
          base: main
          branch: sync/update-repositories-data
          delete-branch: true
          labels: automated-pr
          assignees: tristantheb
          reviewers: tristantheb
